Activation functions

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [44]:
# relu activation
# rectified linear activation, relu introduces linearity by preserving only the +ve values in the output.

class ReLU():
    def forward(self, x):
        self.output = np.maximum(0, x)
        return self.output

In [45]:
relu = ReLU()

In [46]:
xs = np.random.randn(3,2)

In [47]:
xs, relu.forward(xs)

(array([[ 2.12387079,  0.94995042],
        [ 0.40514926,  1.47666774],
        [-0.30929577,  0.53078475]]),
 array([[2.12387079, 0.94995042],
        [0.40514926, 1.47666774],
        [0.        , 0.53078475]]))

In [52]:
# softmax activation is useful at the output layer, the softmax function outputs the 
# probabilitis corresponding to a list of outputs.
class Softmax():
    def forward(self, x):
        ex = np.exp(xs - xs.max(axis=1, keepdims=1))
        self.output = ex/ex.sum(axis=1, keepdims=1)
        return self.output

In [49]:
softmax = Softmax()

In [50]:
softmax.forward(xs)

array([[0.76385291, 0.23614709],
       [0.25511442, 0.74488558],
       [0.30151783, 0.69848217]])

In [53]:
# create a network with activation layers
class DenseLayer:
    def __init__(self, dim_in, dim_out):
        # here we are creating a transposed metrix to avoid transpose at each evaluation of a layer
        # therfore here columns represent the neurons and rows represent the nth input wights of each
        # neuron
        self.weights = np.random.randn(dim_in, dim_out)
        # using zero as bias for sometime
        self.bias = np.zeros((1, dim_out))
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.bias
        return self.output


In [57]:
xs = np.random.randn(3, 5)

layer1 = DenseLayer(5, 3)
layer2 = DenseLayer(3, 3)
relu = ReLU()
softmax = Softmax()

In [62]:
# neural network with two layers and activation functions
output = softmax.forward(layer2.forward(relu.forward(layer1.forward(xs))))
output

array([[0.0618116 , 0.01688004, 0.39124695, 0.360943  , 0.1691184 ],
       [0.35373774, 0.10136901, 0.12571947, 0.33609638, 0.08307739],
       [0.06894986, 0.15125796, 0.49811907, 0.04927064, 0.23240248]])

In [61]:
output.sum(axis=1, keepdims=1)

array([[1.],
       [1.],
       [1.]])