In [21]:
import torch

In [22]:
x = torch.arange(10)

In [23]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
context_length = 5

In [25]:
x[-context_length:] # take last 5

tensor([5, 6, 7, 8, 9])

In [31]:
x1 = torch.stack([x, x], dim=0)

In [32]:
x1

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
x1[:, -context_length:]

tensor([[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]])

In [55]:
torch.tensor([1,2,3,4,5]).unsqueeze(0)

tensor([[1, 2, 3, 4, 5]])

In [41]:
!pip install tiktoken

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 5.0 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [42]:
import tiktoken

In [43]:
tokenizer = tiktoken.get_encoding("gpt2")

In [44]:
start_context = "Hello, I am"

In [49]:
idx = tokenizer.encode(start_context)
idx

[15496, 11, 314, 716]

In [50]:
idx = torch.tensor(idx).unsqueeze(0)
idx

tensor([[15496,    11,   314,   716]])

In [53]:
idx[:, -1024]

IndexError: index -1024 is out of bounds for dimension 1 with size 4