In [1]:
import numpy as np

In [2]:
A = np.matrix("1 2 3; 4 5 6; 7 8 9")

In [3]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
B = np.matrix("1 0 0; 0 1 0; 0 0 1")

In [6]:
B

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [7]:
A @ B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
np.transpose(B)

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [9]:
np.invert(B)

matrix([[-2, -1, -1],
        [-1, -2, -1],
        [-1, -1, -2]])

In [10]:
np.transpose(A)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [11]:
A @ np.transpose(A)

matrix([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]])

In [13]:
C = np.matrix("0 0 1; 0 1 0; 1 0 0")

In [14]:
C

matrix([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])

In [15]:
A @ C

matrix([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]])

In [16]:
np.transpose(A)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [17]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
A.transpose()

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [19]:
A.min()

1

In [20]:
A.max()

9

In [22]:
A.diagonal()

matrix([[1, 5, 9]])

In [23]:
A.getT()

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [24]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
A.view()

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [1]:
A

NameError: name 'A' is not defined

In [27]:
A.shape

(3, 3)