In [2]:
import torch

In [31]:
torch.manual_seed(123)
x1 = torch.ones(2, 3) 
x2 = torch.ones(2, 3) * 2

In [29]:
x1, x2

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.]]))

In [32]:
torch.stack([x1, x2], dim=0)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])

In [27]:
torch.stack((x1, x2), dim=1)

tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[1., 1., 1.],
         [2., 2., 2.]]])