In [1]:
import torch

In [31]:
torch.manual_seed(123)
batch = torch.stack([torch.randint(10, (3, 6)), torch.randint(10, (3, 6))], dim=0)
batch.shape

torch.Size([2, 3, 6])

In [32]:
batch

tensor([[[2, 9, 2, 0, 0, 2],
         [6, 7, 9, 4, 1, 1],
         [6, 1, 2, 9, 4, 1]],

        [[3, 0, 0, 6, 5, 7],
         [9, 2, 1, 6, 0, 6],
         [6, 5, 3, 9, 4, 6]]])

In [33]:
heads = 2
head_dim = 3
batch.view(2, 3, heads, head_dim) # view as 2 heads producing 3 dimensional context vector

tensor([[[[2, 9, 2],
          [0, 0, 2]],

         [[6, 7, 9],
          [4, 1, 1]],

         [[6, 1, 2],
          [9, 4, 1]]],


        [[[3, 0, 0],
          [6, 5, 7]],

         [[9, 2, 1],
          [6, 0, 6]],

         [[6, 5, 3],
          [9, 4, 6]]]])

In [35]:
batch.view(2, 3, heads, head_dim).transpose(1,2)

tensor([[[[2, 9, 2],
          [6, 7, 9],
          [6, 1, 2]],

         [[0, 0, 2],
          [4, 1, 1],
          [9, 4, 1]]],


        [[[3, 0, 0],
          [9, 2, 1],
          [6, 5, 3]],

         [[6, 5, 7],
          [6, 0, 6],
          [9, 4, 6]]]])

In [42]:
in_idx = torch.randint(20, (2, 4))

In [43]:
in_idx.shape

torch.Size([2, 4])

In [41]:
pos = torch.nn.Embedding(4, 3)

In [45]:
pos.weight

Parameter containing:
tensor([[-0.0276,  1.0541,  0.5661],
        [-0.3820,  0.8807,  0.2710],
        [ 0.7694,  0.3453,  1.8979],
        [-0.2357,  0.7885,  0.3208]], requires_grad=True)

In [44]:
pos(torch.arange(0, 4), de)

tensor([[-0.0276,  1.0541,  0.5661],
        [-0.3820,  0.8807,  0.2710],
        [ 0.7694,  0.3453,  1.8979],
        [-0.2357,  0.7885,  0.3208]], grad_fn=<EmbeddingBackward0>)

In [46]:
in_idx.device

device(type='cpu')