In [1]:
import torch 

In [23]:
b_size = 1
n_tokens = 2
dim_in = 6
dim_out = 6
n_heads = 3
dim_head = 2

In [39]:
torch.manual_seed(123)

In [40]:
x = torch.rand(n_tokens, dim_in).unsqueeze(dim=0)

In [41]:
x.shape # batch containing 1 item with 2x6 

torch.Size([1, 2, 6])

In [42]:
x

tensor([[[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665],
         [0.1366, 0.1025, 0.1841, 0.7264, 0.3153, 0.6871]]])

In [44]:
y = x.view(b_size, n_tokens, n_heads, dim_head)
y

tensor([[[[0.2961, 0.5166],
          [0.2517, 0.6886],
          [0.0740, 0.8665]],

         [[0.1366, 0.1025],
          [0.1841, 0.7264],
          [0.3153, 0.6871]]]])

In [45]:
y.shape

torch.Size([1, 2, 3, 2])

In [47]:
keys = y.transpose(1,2)

In [48]:
keys

tensor([[[[0.2961, 0.5166],
          [0.1366, 0.1025]],

         [[0.2517, 0.6886],
          [0.1841, 0.7264]],

         [[0.0740, 0.8665],
          [0.3153, 0.6871]]]])

In [50]:
keys_t = keys.transpose(2,3)

In [51]:
keys_t

tensor([[[[0.2961, 0.1366],
          [0.5166, 0.1025]],

         [[0.2517, 0.1841],
          [0.6886, 0.7264]],

         [[0.0740, 0.3153],
          [0.8665, 0.6871]]]])

In [58]:
attn_scores = keys @ keys_t

In [59]:
attn_scores

tensor([[[[0.3545, 0.0934],
          [0.0934, 0.0292]],

         [[0.5374, 0.5465],
          [0.5465, 0.5616]],

         [[0.7563, 0.6187],
          [0.6187, 0.5715]]]])

In [61]:
mask = torch.triu(torch.ones(n_tokens, n_tokens), diagonal=1)
mask

tensor([[0., 1.],
        [0., 0.]])

In [62]:
attn_scores.masked_fill(mask.bool()[:n_tokens, :n_tokens], -torch.inf)

tensor([[[[0.3545,   -inf],
          [0.0934, 0.0292]],

         [[0.5374,   -inf],
          [0.5465, 0.5616]],

         [[0.7563,   -inf],
          [0.6187, 0.5715]]]])

torch.Size([1, 3, 2, 2])