In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np

In [2]:
g = torch.Generator().manual_seed(2147483647)

In [3]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 20]
logits = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 20]).float() / max(arr)
print(logits)

tensor([0.0500, 0.1000, 0.1500, 0.2000, 0.2500, 0.3000, 0.3500, 0.4000, 0.4500,
        1.0000])


In [4]:
probs = logits.softmax(dim=0)
print(probs)

tensor([0.0732, 0.0769, 0.0808, 0.0850, 0.0893, 0.0939, 0.0987, 0.1038, 0.1091,
        0.1891])


In [12]:
torch.multinomial(probs, num_samples =1, generator = g, replacement=True)

tensor([9])